    package Ventanas;


import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
public class Comidas1 extends javax.swing.JFrame{
    private String sexo;
    private byte edad;
    private float peso;
    private short altura;

    public Comidas1() {
        
        initComponents();
        setLocationRelativeTo(null);//centrar
        setResizable(false);// no cambiar maximizar
        setTitle("Nutrisoft");//NOMBRE A LA PANTALLA
        
       // new Lista().setVisible(true); //desde ventana 2 llamar a ventana 1

        JTextArea txaDes = new JTextArea();
        JTextArea txacena1 = new JTextArea();
        JTextArea txaComida = new JTextArea();
        JTextArea txaSnack = new JTextArea();
        
        
        
        /*Lista lista = new Lista();
        System.out.println(Lista.getText());*/
        
    }
    public void GuardarDatos(String sexo, byte edad, float peso, short altura){
        
    }
    public Comidas1(JTextArea txaCena, JTextArea txaComida, JTextArea txaDes, JTextArea txaSnack) {
        this.txaCena = txaCena;
        this.txaComida = txaComida;
        this.txaDes = txaDes;
        this.txaSnack = txaSnack;
    }

    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(JButton btnCalcular) {
        this.btnCalcular = btnCalcular;
    }

    public JTextArea getTxaCena() {
        return txaCena;
    }

    public void setTxaCena(JTextArea txaCena) {
        this.txaCena = txaCena;
    }

    public JTextArea getTxaComida() {
        return txaComida;
    }

    public void setTxaComida(JTextArea txaComida) {
        this.txaComida = txaComida;
    }

    public JTextArea getTxaDes() {
        return txaDes;
    }

    public void setTxaDes(JTextArea txaDes) {
        this.txaDes = txaDes;
    }

    public JTextArea getTxaSnack() {
        return txaSnack;
    }

    public void setTxaSnack(JTextArea txaSnack) {
        this.txaSnack = txaSnack;
    }

    

    public void setDatos(String sex, byte ed, float pes, short alt) {
        this.sexo = sex;
        this.edad = ed;
        this.peso = pes;
        this.altura = alt;
        System.out.println(sexo+" "+edad+" "+peso+" "+altura);
        
        
    }
    jTextArea1 textareaDesayuo = new jTextArea1();
    public Comidas1(JTextArea jTextArea1) {
        this.txaDes = jTextArea1;
    }
    
    public void txaDes (){
        this.txaDes = txaDes;
    }
    
      
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaCena = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaSnack = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaComida = new javax.swing.JTextArea();
        btnSeleccionar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CounterFood");

        jLabel2.setText("Desayuno");

        jLabel3.setText("Comida");

        jLabel4.setText("Cena");

        jLabel6.setText("Snack");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txaDes.setColumns(20);
        txaDes.setRows(5);
        jScrollPane1.setViewportView(txaDes);

        txaCena.setColumns(20);
        txaCena.setRows(5);
        jScrollPane2.setViewportView(txaCena);

        txaSnack.setColumns(20);
        txaSnack.setRows(5);
        jScrollPane3.setViewportView(txaSnack);

        txaComida.setColumns(20);
        txaComida.setRows(5);
        jScrollPane4.setViewportView(txaComida);

        btnSeleccionar.setText("Seleccionar Alimentos");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel2)
                            .addGap(78, 78, 78)
                            .addComponent(jLabel3)
                            .addGap(97, 97, 97)
                            .addComponent(jLabel4)
                            .addGap(99, 99, 99)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnVolver))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
     Calculadora nF = new Calculadora();
     nF.setVisible(true);       
        nF.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        new Lista().setVisible(true);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new RegistroPaci().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JTextArea txaCena;
    public static javax.swing.JTextArea txaComida;
    public static javax.swing.JTextArea txaDes;
    public static javax.swing.JTextArea txaSnack;
    // End of variables declaration//GEN-END:variables

    /*void txaDes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    void Lista() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void jTextArea1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setDatos(String sexo, int edad, float peso, float altura) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class jTextArea1 {

        public jTextArea1() {
        }
    }

    static class txades {

        public txades() {
        }
    }
}
