package Ventanas;

import Ventanas.Alimento1.Alimentos;
import static Ventanas.Alimento1.Alimentos.arregloAlimentos;
import javax.swing.ImageIcon;

public class OrdenarAlimentos extends javax.swing.JFrame {

    Alimento1 obj_alimentos;
    Alimento1 alimentos;

    /**
     * Creates new form OrdenarAlimentos
     */
    public OrdenarAlimentos() {

        initComponents();
        setLocationRelativeTo(null);//centrar
        setResizable(false);// no cambiar maximizar
        setTitle("Nutrisoft");//NOMBRE A LA PANTALLA
    }
    public void reset(){
        textArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        btnCarbohidratos = new javax.swing.JButton();
        btnCalcio = new javax.swing.JButton();
        btnHierro = new javax.swing.JButton();
        btnFibra = new javax.swing.JButton();
        bntSodio = new javax.swing.JButton();
        btnPotasio = new javax.swing.JButton();
        btnProteina = new javax.swing.JButton();
        btnVC = new javax.swing.JButton();
        btnVb1 = new javax.swing.JButton();
        btnVb2 = new javax.swing.JButton();
        btnVb12 = new javax.swing.JButton();
        btnMagnesio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarbohidratos.setText("Carbohidratos");
        btnCarbohidratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarbohidratosActionPerformed(evt);
            }
        });

        btnCalcio.setText("Calcio");
        btnCalcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcioActionPerformed(evt);
            }
        });

        btnHierro.setText("Hierro");
        btnHierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHierroActionPerformed(evt);
            }
        });

        btnFibra.setText("Fibra");
        btnFibra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibraActionPerformed(evt);
            }
        });

        bntSodio.setText("Sodio");
        bntSodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSodioActionPerformed(evt);
            }
        });

        btnPotasio.setText("Potasio");
        btnPotasio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotasioActionPerformed(evt);
            }
        });

        btnProteina.setText("Proteina");
        btnProteina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProteinaActionPerformed(evt);
            }
        });

        btnVC.setText("Vitamina C");
        btnVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVCActionPerformed(evt);
            }
        });

        btnVb1.setText("Vitamina B1");
        btnVb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVb1ActionPerformed(evt);
            }
        });

        btnVb2.setText("Vitamina B2");
        btnVb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVb2ActionPerformed(evt);
            }
        });

        btnVb12.setText("Vitamina B12");
        btnVb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVb12ActionPerformed(evt);
            }
        });

        btnMagnesio.setText("Magnesio");
        btnMagnesio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagnesioActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 255, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 255, 0));

        jSeparator2.setBackground(new java.awt.Color(102, 255, 0));
        jSeparator2.setForeground(new java.awt.Color(51, 255, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Alimentos Ordenados");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Haga click en los nutrientes a ordenar:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCarbohidratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFibra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntSodio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVb12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHierro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMagnesio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPotasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCalcio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProteina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVC, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))))
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarbohidratos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProteina, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFibra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMagnesio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHierro, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntSodio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPotasio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVb1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVb2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVb12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnVolver)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textArea1 (String ordCarb ){
        OrdenarAlimentos.textArea1.setText(OrdenarAlimentos.textArea1.getText()+ordCarb+"\n");
    }
    private void btnCarbohidratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarbohidratosActionPerformed
        Alimento1 t = new Alimento1();
       // textArea1(Alimentos.imprimirArregloAlimentos(arregloAlimentos));
       Alimento1.Alimentos.selectionSort(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnCarbohidratosActionPerformed

    private void btnProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProteinaActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortProt(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
        }
    }//GEN-LAST:event_btnProteinaActionPerformed

    private void btnFibraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibraActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortFibra(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnFibraActionPerformed

    private void btnCalcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcioActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortCalcio(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnCalcioActionPerformed

    private void btnHierroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHierroActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortHierro(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnHierroActionPerformed

    private void btnMagnesioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagnesioActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortMagnesio(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnMagnesioActionPerformed

    private void bntSodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSodioActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortSodio(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_bntSodioActionPerformed

    private void btnPotasioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotasioActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortPotasio(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnPotasioActionPerformed

    private void btnVb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVb1ActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortVb1(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnVb1ActionPerformed

    private void btnVb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVb2ActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortVb2(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnVb2ActionPerformed

    private void btnVb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVb12ActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortVb12(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnVb12ActionPerformed

    private void btnVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVCActionPerformed
        // TODO add your handling code here:
        Alimento1.Alimentos.selectionSortVbC(arregloAlimentos);
        for (int i = 0; i < arregloAlimentos.length; i++) {
            textArea1(" - " + "." + arregloAlimentos[i].alimento +"  "+ 
                    " - CARBOHIDRATOS: " + arregloAlimentos[i].carb +"  "+ 
                    " - VITAMINA B12: " + arregloAlimentos[i].vb12 +"  "+
                    " - PROTEINA: " + arregloAlimentos[i].prot + "  "+
                    " - FIBRA: " + arregloAlimentos[i].fib + "  "+
                    " - CALCIO: "+ arregloAlimentos[i].cal + "  "+
                    " - HIERRO: " + arregloAlimentos[i].hie +"  "+
                    " - MAGNESIO: " + arregloAlimentos[i].magn +"  "+
                    " - SODIO: " + arregloAlimentos[i].sod +"  "+
                    " - POTASIO: " + arregloAlimentos[i].pot +"  "+
                    "- VITAMINA B1: " + arregloAlimentos[i].vb1+"  "+
                    " - VITAMINA B2: " + arregloAlimentos[i].vb2+"  "+
                    " - VITAMINA C: " + arregloAlimentos[i].vbc);
           
        }
    }//GEN-LAST:event_btnVCActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        //new Comidas1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenarAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSodio;
    private javax.swing.JButton btnCalcio;
    private javax.swing.JButton btnCarbohidratos;
    private javax.swing.JButton btnFibra;
    private javax.swing.JButton btnHierro;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMagnesio;
    private javax.swing.JButton btnPotasio;
    private javax.swing.JButton btnProteina;
    private javax.swing.JButton btnVC;
    private javax.swing.JButton btnVb1;
    private javax.swing.JButton btnVb12;
    private javax.swing.JButton btnVb2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

}
